package team.tangible.app;

import android.app.Application;

import team.tangible.app.DaggerTangibleApplicationComponent;

public final class TangibleApplication extends Application {

    private TangibleApplicationComponent mApplicationComponent;

    /**
     * Reference to the entire application's dependency graph
     * IMPORTANT NOTE: {@code DaggerTangibleApplicationComponent} is auto-generated by Dagger in the
     * build process as such, it may appear as an unresolved reference before building
     * See: https://github.com/JorgeCastilloPrz/Dagger2Scopes/issues/1#issuecomment-93363909
     *
     * PLEASE READ: https://developer.android.com/training/dependency-injection/dagger-android
     */
    public TangibleApplicationComponent getApplicationComponent() {
        if (mApplicationComponent == null) {
            mApplicationComponent = DaggerTangibleApplicationComponent.builder()
                    .setTangibleApplicationModule(new TangibleApplicationModule())
                    .context(this)
                    .build();
        }
        return mApplicationComponent;
    }

    /**
     * Used in testing
     */
    public void setApplicationComponent(TangibleApplicationComponent applicationComponent) {
        mApplicationComponent = applicationComponent;
    }
}
