name: Android APK Build and Upload on Push to Master

on:
  push:
    branches:
      - master

jobs:
  apk:
    name: Generate APK
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Release APK
        run: ./gradlew assemble --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/app-release-unsigned.apk
