name: Android APK Build on Pull Request

on: [ pull_request ]

jobs:
  apk:
    name: Generate APK
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Release APK
        run: ./gradlew assemble --stacktrace
